version: '3.1'
services:
  terraform:
    build:
      context: .
      dockerfile: terra.Dockerfile
  website:
   build:
    context: .
   ports:
    - 80:80
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    volumes:
      - $PWD:/app
    command:
      - --pattern
      - /app/test/unit/*_spec.rb
